### ISSUE TITLE
Undefined method 'stages'

### ISSUE THREAD

**Issue by Atastor** [rvm/rvm1-capistrano3#40]
Stumbling over the following problem: 

```
$ rails -v
Rails 4.1.5

$ rvm version
rvm 1.25.29 (master) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]

$ bundle show capistrano
/Users/michaelp/.rvm/gems/ruby-2.1.2/gems/capistrano-3.2.1

$ bundle show rvm1-capistrano3
/Users/michaelp/.rvm/gems/ruby-2.1.2/gems/rvm1-capistrano3-1.2.6

$ cap staging deploy
cap aborted!
NoMethodError: undefined method `stages' for Capistrano::DSL:Module
/Users/michaelp/.rvm/gems/ruby-2.1.2/gems/rvm1-capistrano3-1.2.6/lib/rvm1/tasks/capistrano3.rake:53:in `<top (required)>'
/Users/michaelp/.rvm/gems/ruby-2.1.2/gems/rvm1-capistrano3-1.2.6/lib/rvm1/capistrano3.rb:1:in `load'
/Users/michaelp/.rvm/gems/ruby-2.1.2/gems/rvm1-capistrano3-1.2.6/lib/rvm1/capistrano3.rb:1:in `<top (required)>'
/Users/michaelp/RubySpielwiese/Frankenberg/Capfile:2:in `require'
/Users/michaelp/RubySpielwiese/Frankenberg/Capfile:2:in `<top (required)>'
/Users/michaelp/.rvm/gems/ruby-2.1.2/gems/capistrano-3.2.1/lib/capistrano/application.rb:15:in `run'
/Users/michaelp/.rvm/gems/ruby-2.1.2/gems/capistrano-3.2.1/bin/cap:3:in `<top (required)>'
/Users/michaelp/.rvm/gems/ruby-2.1.2/bin/cap:23:in `load'
/Users/michaelp/.rvm/gems/ruby-2.1.2/bin/cap:23:in `<main>'
/Users/michaelp/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
/Users/michaelp/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
```

**Comment by khanimdad** [comment]
I have the same problem but with rbevn, but not sure how to fix, any idea?

**Comment by mpapis** [comment]
@khanimdad are you sure you followed all instructions form Readme? - if yes please open a new ticket

**Comment by fdwillis** [comment]
Yes, need help...
