### ISSUE TITLE
deploy fails with relative :deploy_to

### ISSUE THREAD

**Issue by ivan-kolmychek** [rvm/rvm1-capistrano3#48]
Hi.

`1.2.6` understands relative paths well, but new `1.3.2.2` fails on `deploy:check`

Somewhere in deployment configuration:

```
set :deploy_to, '~/rvm1cap3test'
```

```
[ivko@thinkpad-e530 rvm1cap3test]$ bundle exec cap staging deploy:check                                                                                                
INFO[fcff978e] Running /usr/bin/env mkdir -p ~/rvm1cap3test/rvm1scripts/ on <server host here>
DEBUG[fcff978e] Command: /usr/bin/env mkdir -p ~/rvm1cap3test/rvm1scripts/
INFO[fcff978e] Finished in 3.512 seconds with exit status 0 (successful).
DEBUGUploading /home/ivko/rvm1cap3test/vendor/bundle/ruby/2.1.0/gems/rvm1-capistrano3-1.3.2.2/script/rvm-auto.sh 0.0%
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing on host <server host here>: scp: ~/rvm1cap3test/rvm1scripts/rvm-auto.sh: No such file or directory
/home/ivko/rvm1cap3test/vendor/bundle/ruby/2.1.0/gems/net-scp-1.2.1/lib/net/scp.rb:398:in `await_response_state'
/home/ivko/rvm1cap3test/vendor/bundle/ruby/2.1.0/gems/net-scp-1.2.1/lib/net/scp.rb:369:in `block (3 levels) in start_command'
/home/ivko/rvm1cap3test/vendor/bundle/ruby/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/channel.rb:311:in `call'
/home/ivko/rvm1cap3test/vendor/bundle/ruby/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/channel.rb:311:in `process'
/home/ivko/rvm1cap3test/vendor/bundle/ruby/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:222:in `block in preprocess'
/home/ivko/rvm1cap3test/vendor/bundle/ruby/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:222:in `each'
/home/ivko/rvm1cap3test/vendor/bundle/ruby/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:222:in `preprocess'
/home/ivko/rvm1cap3test/vendor/bundle/ruby/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:205:in `process'
/home/ivko/rvm1cap3test/vendor/bundle/ruby/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `block in loop'
/home/ivko/rvm1cap3test/vendor/bundle/ruby/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
/home/ivko/rvm1cap3test/vendor/bundle/ruby/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
/home/ivko/rvm1cap3test/vendor/bundle/ruby/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/channel.rb:269:in `wait'
/home/ivko/rvm1cap3test/vendor/bundle/ruby/2.1.0/gems/net-scp-1.2.1/lib/net/scp.rb:284:in `upload!'
/home/ivko/rvm1cap3test/vendor/bundle/ruby/2.1.0/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:83:in `block in upload!'
/home/ivko/rvm1cap3test/vendor/bundle/ruby/2.1.0/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:186:in `with_ssh'
/home/ivko/rvm1cap3test/vendor/bundle/ruby/2.1.0/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:82:in `upload!'
/home/ivko/rvm1cap3test/vendor/bundle/ruby/2.1.0/gems/rvm1-capistrano3-1.3.2.2/lib/rvm1/tasks/capistrano3.rake:6:in `block (3 levels) in <top (required)>'
/home/ivko/rvm1cap3test/vendor/bundle/ruby/2.1.0/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:54:in `instance_exec'
/home/ivko/rvm1cap3test/vendor/bundle/ruby/2.1.0/gems/sshkit-1.5.1/lib/sshkit/backends/netssh.rb:54:in `run'
/home/ivko/rvm1cap3test/vendor/bundle/ruby/2.1.0/gems/sshkit-1.5.1/lib/sshkit/runners/parallel.rb:13:in `block (2 levels) in execute'
scp: ~/rvm1cap3test/rvm1scripts/rvm-auto.sh: No such file or directory
```

full path (`/home/someuserhere/rvm1cap3test`) works just great.

**Comment by casertap** [comment]
+1
