### ISSUE TITLE
 Could not find 'bundler' (>= 0)

### ISSUE THREAD

**Issue by emaillenin** [rvm/rvm1-capistrano3#62]
deploy.rb - https://gist.github.com/emaillenin/32b25f15a607ec2bf5c2
deploy/production.rb - https://gist.github.com/emaillenin/fa0e73497f46b792d7c7
output - https://gist.github.com/emaillenin/c2d704be801bd5b0a7de
error:

````
INFO[d396df32] Running /var/www/duggout/rvm1scripts/rvm-auto.sh . bundle install --binstubs /var/www/duggout/shared/bin --path /var/www/duggout/shared/bundle --without development test --deployment --quiet on 96.126.114.83
DEBUG[d396df32] Command: cd /var/www/duggout/releases/20150904121559 && /var/www/duggout/rvm1scripts/rvm-auto.sh . bundle install --binstubs /var/www/duggout/shared/bin --path /var/www/duggout/shared/bundle --without development test --deployment --quiet
DEBUG[d396df32] 	/usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'bundler' (>= 0) among 11 total gem(s) (Gem::LoadError)
DEBUG[d396df32] 	Checked in 'GEM_PATH=/home/deployer/.rvm/gems/ruby-2.2.3@duggout-app:/home/deployer/.rvm/gems/ruby-2.2.3@global', execute `gem env` for more information
DEBUG[d396df32] 		from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/dependency.rb:324:in `to_spec'
DEBUG[d396df32] 		from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_gem.rb:64:in `gem'
DEBUG[d396df32] 		from /usr/local/bin/bundle:18:in `<main>'
DEBUG[d396df32] 		from /usr/local/bin/ruby_executable_hooks1.9.1:15:in `eval'
DEBUG[d396df32] 		from /usr/local/bin/ruby_executable_hooks1.9.1:15:in `<main>'
````

**Comment by emaillenin** [comment]
cc @mpapis

**Comment by mpapis** [comment]
you need to install `bundler` if it is your dependency
