### ISSUE TITLE
Unable to deploy to new server

### ISSUE THREAD

**Issue by pcasa** [rvm/rvm1-capistrano3#70]
Tried running:
cap staging rvm1:check --trace

```
** Invoke staging (first_time)
** Execute staging
** Invoke load:defaults (first_time)
** Execute load:defaults
** Invoke rvm1:hook (first_time)
** Execute rvm1:hook
INFO [3fc371fa] Running /usr/bin/env mkdir -p / as ec2-user@SOME_IP_ADDRESS
DEBUG [3fc371fa] Command: ( export RVM_BIN_PATH="~/.rvm/bin" ; /usr/bin/env mkdir -p / )
INFO [3fc371fa] Finished in 0.539 seconds with exit status 0 (successful).
DEBUG Uploading /Users/MY_USER_NAME/.rvm/gems/ruby-2.2.1/gems/rvm1-capistrano3-1.4.0/script/rvm-auto.sh 0.0%
cap aborted!
scp: /rvm-auto.sh: Permission denied
/Users/MY_USER_NAME/.rvm/gems/ruby-2.2.1/gems/net-scp-1.2.1/lib/net/scp.rb:398:in `await_response_state'
/Users/MY_USER_NAME/.rvm/gems/ruby-2.2.1/gems/net-scp-1.2.1/lib/net/scp.rb:369:in `block (3 levels) in start_command'
/Users/MY_USER_NAME/.rvm/gems/ruby-2.2.1/gems/net-ssh-3.0.1/lib/net/ssh/connection/channel.rb:311:in `call'
/Users/MY_USER_NAME/.rvm/gems/ruby-2.2.1/gems/net-ssh-3.0.1/lib/net/ssh/connection/channel.rb:311:in `process'
/Users/MY_USER_NAME/.rvm/gems/ruby-2.2.1/gems/net-ssh-3.0.1/lib/net/ssh/connection/session.rb:223:in `block in preprocess'
/Users/MY_USER_NAME/.rvm/gems/ruby-2.2.1/gems/net-ssh-3.0.1/lib/net/ssh/connection/session.rb:223:in `each'
/Users/MY_USER_NAME/.rvm/gems/ruby-2.2.1/gems/net-ssh-3.0.1/lib/net/ssh/connection/session.rb:223:in `preprocess'
/Users/MY_USER_NAME/.rvm/gems/ruby-2.2.1/gems/net-ssh-3.0.1/lib/net/ssh/connection/session.rb:206:in `process'
/Users/MY_USER_NAME/.rvm/gems/ruby-2.2.1/gems/net-ssh-3.0.1/lib/net/ssh/connection/session.rb:170:in `block in loop'
/Users/MY_USER_NAME/.rvm/gems/ruby-2.2.1/gems/net-ssh-3.0.1/lib/net/ssh/connection/session.rb:170:in `loop'
/Users/MY_USER_NAME/.rvm/gems/ruby-2.2.1/gems/net-ssh-3.0.1/lib/net/ssh/connection/session.rb:170:in `loop'
/Users/MY_USER_NAME/.rvm/gems/ruby-2.2.1/gems/net-ssh-3.0.1/lib/net/ssh/connection/channel.rb:269:in `wait'
/Users/MY_USER_NAME/.rvm/gems/ruby-2.2.1/gems/net-scp-1.2.1/lib/net/scp.rb:284:in `upload!'
/Users/MY_USER_NAME/.rvm/gems/ruby-2.2.1/gems/sshkit-1.8.1/lib/sshkit/backends/netssh.rb:34:in `block in upload!'
/Users/MY_USER_NAME/.rvm/gems/ruby-2.2.1/gems/sshkit-1.8.1/lib/sshkit/backends/netssh.rb:141:in `with_ssh'
/Users/MY_USER_NAME/.rvm/gems/ruby-2.2.1/gems/sshkit-1.8.1/lib/sshkit/backends/netssh.rb:33:in `upload!'
/Users/MY_USER_NAME/.rvm/gems/ruby-2.2.1/gems/rvm1-capistrano3-1.4.0/lib/rvm1/tasks/capistrano3.rake:6:in `block (3 levels) in <top (required)>'
/Users/MY_USER_NAME/.rvm/gems/ruby-2.2.1/gems/sshkit-1.8.1/lib/sshkit/backends/abstract.rb:15:in `instance_exec'
/Users/MY_USER_NAME/.rvm/gems/ruby-2.2.1/gems/sshkit-1.8.1/lib/sshkit/backends/abstract.rb:15:in `run'
/Users/MY_USER_NAME/.rvm/gems/ruby-2.2.1/gems/sshkit-1.8.1/lib/sshkit/runners/parallel.rb:13:in `block (2 levels) in execute'
Tasks: TOP => rvm1:hook
```

**Comment by pcasa** [comment]
I tried adding 
```set :rvm1_auto_script_path, '/tmp/my-rvm-auto``` 
and that helped, but now get 

```
INFO Uploading /Users/MY_USER_NAME/.rvm/gems/ruby-2.2.1/gems/rvm1-capistrano3-1.4.0/script/rvm-auto.sh 100.0%
INFO [dd1b5d93] Running /usr/bin/env chmod +x /tmp/my-rvm-auto/rvm-auto.sh as ec2-user@SOME_IP_ADDRESS
DEBUG [dd1b5d93] Command: ( export RVM_BIN_PATH="~/.rvm/bin" ; /usr/bin/env chmod +x /tmp/my-rvm-auto/rvm-auto.sh )
INFO [dd1b5d93] Finished in 0.067 seconds with exit status 0 (successful).
(Backtrace restricted to imported tasks)
cap aborted!
NoMethodError: undefined method `each' for nil:NilClass

Tasks: TOP => rvm1:hook
```
