### ISSUE TITLE
Including rvm1-capistrano3 gem breaks local rails console/server

### ISSUE THREAD

**Issue by glassputan** [rvm/rvm1-capistrano3#79]
Really strange, if I include the gem in my Gemfile, I can no longer run the local console or WebBrick server.  By commenting it out, they run without issue.  Not sure what to do here as nothing changes other than including or excluding the gem.  

‹master*›$ rails s
/usr/local/rvm/gems/ruby-2.4.0@hulmevillesoccer/gems/rvm1-capistrano3-1.4.0/lib/rvm1/tasks/capistrano3.rake:33:in `block in <top (required)>': undefined method `before' for main:Object (NoMethodError)
        from /usr/local/rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/task_manager.rb:205:in `in_namespace'
        from /usr/local/rvm/gems/ruby-2.4.0@global/gems/rake-12.0.0/lib/rake/dsl_definition.rb:140:in `namespace'
        from /usr/local/rvm/gems/ruby-2.4.0@hulmevillesoccer/gems/rvm1-capistrano3-1.4.0/lib/rvm1/tasks/capistrano3.rake:1:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.4.0@hulmevillesoccer/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `load'
        from /usr/local/rvm/gems/ruby-2.4.0@hulmevillesoccer/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `block in load'
        from /usr/local/rvm/gems/ruby-2.4.0@hulmevillesoccer/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:259:in `load_dependency'
        from /usr/local/rvm/gems/ruby-2.4.0@hulmevillesoccer/gems/activesupport-5.0.2/lib/active_support/dependencies.rb:287:in `load'
        from /usr/local/rvm/gems/ruby-2.4.0@hulmevillesoccer/gems/rvm1-capistrano3-1.4.0/lib/rvm1/capistrano3.rb:1:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.4.0@hulmevillesoccer/gems/bundler-1.14.6/lib/bundler/runtime.rb:105:in `require'
        from /usr/local/rvm/gems/ruby-2.4.0@hulmevillesoccer/gems/bundler-1.14.6/lib/bundler/runtime.rb:105:in `rescue in block in require'
        from /usr/local/rvm/gems/ruby-2.4.0@hulmevillesoccer/gems/bundler-1.14.6/lib/bundler/runtime.rb:82:in `block in require'
        from /usr/local/rvm/gems/ruby-2.4.0@hulmevillesoccer/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each'
        from /usr/local/rvm/gems/ruby-2.4.0@hulmevillesoccer/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require'
        from /usr/local/rvm/gems/ruby-2.4.0@hulmevillesoccer/gems/bundler-1.14.6/lib/bundler.rb:107:in `require'
        from /home/scott/HSC/hulmevillesoccer/config/application.rb:8:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.4.0@hulmevillesoccer/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:88:in `require'
        from /usr/local/rvm/gems/ruby-2.4.0@hulmevillesoccer/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:88:in `block in server'
        from /usr/local/rvm/gems/ruby-2.4.0@hulmevillesoccer/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:85:in `tap'
        from /usr/local/rvm/gems/ruby-2.4.0@hulmevillesoccer/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:85:in `server'
        from /usr/local/rvm/gems/ruby-2.4.0@hulmevillesoccer/gems/railties-5.0.2/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        from /usr/local/rvm/gems/ruby-2.4.0@hulmevillesoccer/gems/railties-5.0.2/lib/rails/commands.rb:18:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'

**Comment by tabloludo** [comment]
I am running into this same issue 3+ years later and the only fix seems to be to comment out the gem as mentioned.

**Comment by fsuneuro** [comment]
I just ran into the error as well.
